name: 自动部署

on:
  push:
    branches: [master,dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 检出分支
        uses: actions/checkout@v3

      - name: 2. 安装jdk环境
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'adopt' #发行版
          java-version: '8' #版本号
          cache: 'maven' #缓存
      - name: 3. 构建jar包
        run: mvn -B package --file pom.xml

      - name: 4. 推送到服务器
        uses: ilCollez/ssh-scp-deploy@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }} #ip
          port: ${{ secrets.SERVER_PORT }} #端口
          username: ${{ secrets.SERVER_USER }} #用户名
          key: ${{ secrets.SERVER_ACCESS_TOKEN }} #服务器密钥
          files: | #上传文件
              target/*.jar
              start.sh
          remote-path: ${{ secrets.SERVER_TARGET }} #远程路径
          clean: true #是否清理远程路径
          after-upload: |
              sh start.sh restart
